# Diagonalize Circulant Matrix

Let $\bold{H}_{circ}$ be a circulant matrix constructed by vector $\bold{h}$ of size $N$,

$\bold{H}_{circ} = \bold{F}^H \bold{\Lambda} \bold{F}$, where $\bold{F}$ is the unitary $N$-point DFT matrix, and $\bold{\Lambda} = Diag(\sqrt{N} \bold{F} \bold{h}_{padded}) = Diag(FFT(\bold{h}_{padded}))$. 

Note that $\bold{h}_{padded}$ has length of $N$, and $FFT$ is non-unitary DFT transformation.

Therefore, 
$\bold{\Lambda} = \bold{F} \bold{H}_{circ} \bold{F}^H = Diag(\sqrt{N} \bold{F} \bold{h}_{padded}) = Diag(FFT(\bold{h}_{padded}))$

Application: By having any $\bold{H}_{circ}$, we can use $\bold{F}$ to diagnoalize it. 
To this point, we can directly estimate orthogonal channel.

In [ ]:
import numpy as np

def circulant(x):
    A = np.zeros([x.size, x.size], dtype=int)
    for i in range(x.size):
        A[:,i] = x
        x = np.concat([np.array([x[-1]]), x[:-1]])
    return A

def x_padded(x, N):
    y = np.zeros(N)
    y[:x.size] = x
    return y

N = 5
n_tap = 3
F = np.fft.fft(np.eye(N), norm='ortho')
x = np.random.randint(1, 10, n_tap)
h = x_padded(x, N)
H_circ = circulant(h)
print("H_circ:\n\n{}".format(H_circ))

H_circ:

[[7 0 0 6 2]
 [2 7 0 0 6]
 [6 2 7 0 0]
 [0 6 2 7 0]
 [0 0 6 2 7]]


In [6]:
H_circ = np.complex64(H_circ)
Lambda_ = F @ H_circ @ F.conj().T   # This Lambda_ is diagonal but not equal to h
g = np.diagonal(Lambda_)
Lambda = np.diag(g)

print("Lambda:\n\n{}".format(Lambda))

Lambda:

[[15.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          2.76393202-5.42882455j  0.        +0.j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          7.23606798+4.53076859j
   0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   7.23606798-4.53076859j  0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          2.76393202+5.42882455j]]


In [7]:
# Fouier Transform of h
Fh01 = F @ h * np.sqrt(N)
Fh02 = np.fft.fft(h)

h_est = np.fft.ifft(g)

print("g:\n{}\n".format(g))
print("Fh02:\n{}\n".format(Fh02))
print("h_estimate:\n{}\n".format(h_est))
print("Difference:\n{}".format(np.sum(np.abs(g - Fh01))))

g:
[15.        +0.j          2.76393202-5.42882455j  7.23606798+4.53076859j
  7.23606798-4.53076859j  2.76393202+5.42882455j]

Fh02:
[15.        +0.j          2.76393202-5.42882455j  7.23606798+4.53076859j
  7.23606798-4.53076859j  2.76393202+5.42882455j]

h_estimate:
[7.+0.j 2.+0.j 6.+0.j 0.+0.j 0.+0.j]

Difference:
8.531443352190129e-15


In [8]:
# Estimate h from Lambda
h_est = np.fft.ifft(g)

print("h_est:\n{}\n".format(h_est))
print("Difference:\n{}".format(np.sum(np.abs(h_est - h))))

h_est:
[7.+0.j 2.+0.j 6.+0.j 0.+0.j 0.+0.j]

Difference:
1.5543122344752192e-15


In [10]:
g_est = np.fft.fft(h)
print(g_est)
print(g)

[15.        +0.j          2.76393202-5.42882455j  7.23606798+4.53076859j
  7.23606798-4.53076859j  2.76393202+5.42882455j]
[15.        +0.j          2.76393202-5.42882455j  7.23606798+4.53076859j
  7.23606798-4.53076859j  2.76393202+5.42882455j]
